real_estate:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /Users/abhijithm/Documents/Code/Scrapping/real_estate_pipeline/data/warehouse.duckdb
      extensions:
        - delta
      threads: 4
